config/routes.rb
Rails.application.routes.draw do
  resources :leads, :messages, :segments

  get 'users/index'

  get 'users/:id/dashboard' => 'users#dashboard'

  devise_for :users
  get 'home/index'
  get 'home/visits'

  root 'home#index'

end

app/models/ahoy/message.rb
module Ahoy
  class Message < ActiveRecord::Base
    self.table_name = "ahoy_messages"

    belongs_to :user, AhoyEmail.belongs_to.merge(polymorphic: true)

    def self.find_users(query)
      self.where.not(user_id: nil).where("#{query[:key]} #{query[:pattern_match]} ?", query[:pattern])
    end

    def self.find_users_not(query)
      self.where.not(user_id: nil).where.not("#{query[:key]} #{query[:pattern_match]} ?", query[:pattern])
    end

  end
end

app/models/message.rb
class Message < ActiveRecord::Base

  def send_email(recipient)
    UserMailer.basic_email(recipient, self).deliver_now
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def show
    @message = Message.find params[:id]
    @send_results = Ahoy::Message.where message_id: params[:id]
  end

  def edit
    @message = Message.find params[:id]
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new message_params

    @message.save
    redirect_to @message
  end

  def update
    @message = Message.find params[:id]

    if @message.update(message_params)
      redirect_to @message
    else
      render 'edit'
    end
  end

  private

  def message_params
    params.require(:message).permit(:from_name, :from_email, :subject, :content)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/edit.html.erb
<%= form_for :message, url: message_path(@message), method: :patch do |f| %>
  <p>From: <%= f.text_field :from_name %></p>
  <p>From email: <%= f.text_field :from_email %></p>
  <p>Subject: <%= f.text_field :subject %></p>
  <p>Content</p>
  <p><%= f.text_area :content, class: "tinymce", rows: 40, cols: 120 %></p>
  <%= f.submit "Update" %>
<% end %>

<!-- Load and initialize TinyMCE -->
<%= tinymce_assets %>
<%= tinymce %>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>

<% @messages.each do |message| %>
  <p><%= link_to message.subject, message_path(message) %></p>
<% end %>

app/views/messages/new.html.erb
<%= form_for @message, url: {action: "create"} do |f| %>
  <p>From: <%= f.text_field :from_name %></p>
  <p>From email: <%= f.text_field :from_email %></p>
  <p>Subject: <%= f.text_field :subject %></p>
  <p>Content</p>
  <p><%= f.text_area :content, class: "tinymce", rows: 40, cols: 120 %></p>
  <%= f.submit "Create" %>
<% end %>

<!-- Load and initialize TinyMCE -->
<%= tinymce_assets %>
<%= tinymce %>

app/views/messages/show.html.erb
<h1>Messages#show</h1>
<p>Find me in app/views/messages/show.html.erb</p>

<p>From: <%= @message.from_name %> (<%= @message.from_email %>)</p>
<p>Subject: <%= @message.subject %></p>
<p>Preview:</p>
<%= raw @message.content %>
<hr/>
<table>
  <tr>
    <th>Recipient</th>
    <th>Sent at</th>
    <th>Opened at</th>
    <th>Clicked at</th>
  </tr>
  <% @send_results.each do |msg| %>
    <tr>
      <td>
        <%= msg.to %>
      </td>
      <td>
        <%= msg.sent_at %>
      </td>
      <td>
        <%= msg.opened_at %>
      </td>
      <td>
        <%= msg.clicked_at %>
      </td>
    </tr>
    <% end %>
  </table>