config/routes.rb
Rails.application.routes.draw do
  resources :leads, :messages, :segments

  get 'users/index'

  get 'users/:id/dashboard' => 'users#dashboard'

  devise_for :users
  get 'home/index'
  get 'home/visits'

  root 'home#index'

end

app/models/segment.rb
class Segment < ActiveRecord::Base
  serialize :filters

  has_and_belongs_to_many :users
  validates :filters, presence: true

  after_update :build_workflows

  def build
    segment_builder = BuildSegment.new(self)
    segment_builder.call
  end

  def self.build_all
    Segment.all.each do |segment|
      segment_builder = BuildSegment.new(segment)
      segment_builder.call
    end
  end

  def self.find_users(query)
    self.where(id: query[:pattern])
  end

  def self.find_users_not(query)
    self.where.not(id: query[:pattern])
  end

  def build_workflows
    Workflow.each do |workflow|
      workflow.build
    end
  end

  def self.example2
    # segment has many filters
    # filters have many rules
    # rules have many hashes of parameters (type, url, title etc)
    # serialize filters

    filters = [
      [
        { name: "$view",
          match: "^",
          properties: {
            page: '/messages',
          }
        }, # AND
      ]
    ]

    Segment.create(filters: filters)
  end
  def self.example
    # segment has many filters
    # filters have many rules
    # rules have many hashes of parameters (type, url, title etc)
    # serialize filters

    filters = [
      [
        { name: "$view",
          match: "^",
          properties: {
            page: '/messages',
          }
        }, # AND
        { name: "$view",
          match: "$",
          properties: {
            page: '1',
          }
        }
      ], # OR
      [
        { name: "$view",
          match: "!",
          properties: {
            page: '/messages/1',
          }
        }
      ], # OR
      [
        { name: "$view",
          match: "~",
          properties: {
            url: 'param=test',
          }
        }
      ], # OR
      [
        { name: "$email",
          match: "~",
          properties: {
            subject: "Example Message"
          },
        }, # AND
        {
          name: "$email",
          match: "#",
          properties: {
            to: "patryk.kalinowski"
          }
        }
      ]
    ]

    Segment.create(filters: filters)
  end
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  def index
    @segments = Segment.all
  end

  def show
    @segment = Segment.find params[:id]
    form_labels = {
      name: ['$view'],
      match: ['~', '$', '!', '^', '#', '!^', '!$', 'empty', '!empty'],
      property: ['page', 'url']
    }

    @options_for_select_match = Array.new
    form_labels[:match].each do |match|
      @options_for_select_match << [t("segments.filters.matches.#{match}"), match]
    end

    @options_for_select_name = Array.new
    form_labels[:name].each do |name|
      @options_for_select_name << [t("segments.filters.names.#{name}"), name]
    end

    @options_for_select_property = Array.new
    form_labels[:property].each do |property|
      @options_for_select_property << [t("segments.filters.properties.#{property}"), property]
    end
  end



end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/index.html.erb
<% @segments.each do |segment| %>
  <h1><%= link_to "Segment #{segment.id}", segment_path(segment) %></h1>
  <p>Filters:</p>
  <% segment.filters.each do |filter| %>
    <div class="small-5 callout">
      <% filter.each do |rule| %>
        <div class="callout">
          <p><%= rule[:name] %></p>
          <p><%= rule[:match] %></p>
          <p><%= rule[:properties] %></p>
        </div>
      <% end %>
    </div>
    <p>OR</p>
  <% end %>


<% end %>

app/views/segments/show.html.erb
<h1>Segment <%= @segment.id %></h1>

<div class="row">
  <div class="small-2 large-4 columns">
    <h2>Filters:</h2>
      <% @segment.filters.each do |filter| %>
        <div class="small-12 callout">
          <% filter.each do |rule| %>
            <div class="callout">
              <p>options_for_select: NAME</p>
              <%= options_for_select(@options_for_select_name) %>

              <hr/>
              <p>Options for select: MATCH</p>
              <%= options_for_select(@options_for_select_match) %>

              <hr/>
              <p>options_for_select: PROPERTY</p>
              <%= options_for_select(@options_for_select_property) %>
            </div>
          <% end %>
        </div>
      <% end %>
  </div>
  <div class="small-4 large-4 columns">
    <h2>Users in segment:</h2>
    <% @segment.users.each do |user| %>
      <div class="callout">
        <p><%= "#{user.id}: #{user.identity} (#{user.email})" %></p>
      </div>
    <% end %>
  </div>
</div